# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference

# https://circleci.com/docs/configuration-reference/#resourceclass
version: 2.1
jobs:
  test:
    machine: true
    resource_class: jheck90/dance-judging
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          working_directory: /var/opt/circleci/tmp
          shell: /bin/sh
          command: |
            echo Running test
            mkdir -p /tmp/test-results
  # build:
  #   machine: true
  #   resource_class: jheck90/dance-judging
  #   steps:
  #     - checkout
  #     # Replace this with steps to build a package, or executable
  #     - run:
  #         name: Build an artifact
  #         command: touch example.txt
  #     - store_artifacts:
  #         path: example.txt
  # deploy:
  #   machine: true
  #   resource_class: jheck90/dance-judging
  #   steps:
  #     # Replace this with steps to deploy to users
  #     - run:
  #         name: deploy
  #         command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
